name = "FetchOpenMLData"
uuid = "3181ac60-05e2-4849-b670-ade75aab7d5b"
authors = ["Thura Z."]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
